"Jefferson Robins" is a fictional writer, the result of applying BACON to the works of the American poet Robinson Jeffers.

This directory contains some of the poems written by "Jefferson Robins", i.e. generated by BACON after generating a probabilistic model of Robinson Jeffer's linguistic style
